from enum import Enum

class PromptType(Enum):
    SYSTEM_CHECK_USER_NEED = "SYSTEM_CHECK_USER_NEED"
    SYSTEM_RESEARCH = "SYSTEM_RESEARCH"
    SYSTEM_SUMMARY_WEB_CONTENT = "SYSTEM_SUMMARY_WEB_CONTENT"