from enum import Enum

class PromptType(Enum):
    START_RESEARCH = "START_RESEARCH"
    SYSTEM_CHECK_USER_NEED = "SYSTEM_CHECK_USER_NEED"
    SYSTEM_RESEARCH = "SYSTEM_RESEARCH"
    SYSTEM_RESEARCH_COMPRESS_SYSTEM = "SYSTEM_RESEARCH_COMPRESS_SYSTEM"
    SYSTEM_RESEARCH_COMPRESS_HUMAN = "SYSTEM_RESEARCH_COMPRESS_HUMAN"
    SYSTEM_SUMMARY_WEB_CONTENT = "SYSTEM_SUMMARY_WEB_CONTENT"
    SYSTEM_SUPERVISOR = "SYSTEM_SUPERVISOR"
    FINAL_PEPORT = "FINAL_PEPORT"